package au.com.elied.vitalsignal.reasoning

enum class ReasoningDeliveryState { DELIVERABLE, ABSTAINED, SAFE_FALLBACK }

enum class ReasoningOrchestrationFailure {
    NONE,
    HEALTH_STATE_AUTHORITY_REJECTED,
    POLICY_REJECTED,
    MODEL_UNAVAILABLE,
    AUDIT_COMMIT_FAILED,
}

class ReasoningAuditRecord(
    val inputSnapshotSha256: String,
    val candidateSha256: String?,
    val disposition: ReasoningDisposition,
    policyFailureCodes: Set<ReasoningFailureCode>,
    val orchestrationFailure: ReasoningOrchestrationFailure,
    val authorityFailureCode: HealthStateAuthorityFailureCode?,
    val runReceipt: OllamaRunReceipt?,
    val completedAtEpochMillis: Long,
    val policyVersion: String = "local-reasoning-orchestrator-v2",
) {
    val policyFailureCodes: Set<ReasoningFailureCode> = java.util.Set.copyOf(policyFailureCodes)

    init {
        requireSha256(inputSnapshotSha256, "audit snapshot hash")
        require(candidateSha256 == null || candidateSha256.matches(Regex("[a-f0-9]{64}")))
        require(
            (orchestrationFailure == ReasoningOrchestrationFailure.HEALTH_STATE_AUTHORITY_REJECTED) ==
                (authorityFailureCode != null),
        )
        require(completedAtEpochMillis > 0L)
        require(policyVersion.isNotBlank())
    }
}

fun interface ReasoningAuditSink {
    /** True only after a durable encrypted commit. */
    fun commit(record: ReasoningAuditRecord): Boolean
}

class VerifiedReasoningOutcome internal constructor(
    val state: ReasoningDeliveryState,
    /** Present only after authority/policy pass and durable audit commit. */
    candidate: LocalReasoningCandidate?,
    val runReceipt: OllamaRunReceipt?,
    policyFailureCodes: Set<ReasoningFailureCode>,
    val orchestrationFailure: ReasoningOrchestrationFailure,
    val authorityFailureCode: HealthStateAuthorityFailureCode?,
    /** Reviewed static UI copy; never generated by the model. */
    val safeTemplateId: String?,
) {
    private val candidateSnapshot = candidate?.deepCopyForProvider()
    val candidate: LocalReasoningCandidate? get() = candidateSnapshot?.deepCopyForProvider()
    val policyFailureCodes: Set<ReasoningFailureCode> = java.util.Set.copyOf(policyFailureCodes)

    init {
        require((state == ReasoningDeliveryState.DELIVERABLE) == (candidate != null))
        require((state == ReasoningDeliveryState.SAFE_FALLBACK) == (safeTemplateId != null))
        require(
            (orchestrationFailure == ReasoningOrchestrationFailure.HEALTH_STATE_AUTHORITY_REJECTED) ==
                (authorityFailureCode != null),
        )
    }
}

/**
 * Runs an optional local model behind signed packet authority, deterministic
 * policy and durable audit boundaries. Authority is checked before model use
 * and again after generation, immediately before a result can be audited for
 * delivery.
 */
class VerifiedLocalReasoningOrchestrator(
    private val gateway: LocalReasoningGateway,
    private val authority: HealthStatePacketAuthority,
    private val policy: LocalReasoningPolicy,
    private val auditSink: ReasoningAuditSink,
    private val nowEpochMillis: () -> Long,
) {
    fun run(packet: SignedHealthStatePacket): VerifiedReasoningOutcome {
        val packetSha256 = packet.canonicalPayloadSha256()
        val request = try {
            authority.verify(packet)
        } catch (rejected: HealthStateAuthorityException) {
            return authorityRejected(packetSha256, rejected.failureCode)
        }

        val generated = try {
            val (gatewayCandidate, receipt) = gateway.generate(request)
            gatewayCandidate.immutableLocalSnapshot() to receipt
        } catch (_: Exception) {
            val audit = ReasoningAuditRecord(
                inputSnapshotSha256 = request.inputSnapshotSha256,
                candidateSha256 = null,
                disposition = ReasoningDisposition.ABSTAIN,
                policyFailureCodes = emptySet(),
                orchestrationFailure = ReasoningOrchestrationFailure.MODEL_UNAVAILABLE,
                authorityFailureCode = null,
                runReceipt = null,
                completedAtEpochMillis = nowEpochMillis(),
            )
            val committed = auditSink.commit(audit)
            return safeFallback(
                if (committed) {
                    ReasoningOrchestrationFailure.MODEL_UNAVAILABLE
                } else {
                    ReasoningOrchestrationFailure.AUDIT_COMMIT_FAILED
                },
            )
        }

        val (candidate, receipt) = generated
        val deliveryRequest = try {
            authority.verify(packet)
        } catch (rejected: HealthStateAuthorityException) {
            return authorityRejected(
                snapshotSha256 = packetSha256,
                authorityFailure = rejected.failureCode,
                receipt = receipt,
            )
        }

        val validation = policy.validate(deliveryRequest, candidate)
        val policyRejected = validation.disposition == ReasoningDisposition.REWRITE
        val audit = ReasoningAuditRecord(
            inputSnapshotSha256 = deliveryRequest.inputSnapshotSha256,
            candidateSha256 = CanonicalReasoningCandidate.sha256(candidate),
            disposition = validation.disposition,
            policyFailureCodes = validation.failureCodes,
            orchestrationFailure = if (policyRejected) {
                ReasoningOrchestrationFailure.POLICY_REJECTED
            } else {
                ReasoningOrchestrationFailure.NONE
            },
            authorityFailureCode = null,
            runReceipt = receipt,
            completedAtEpochMillis = nowEpochMillis(),
        )
        if (!auditSink.commit(audit)) {
            return safeFallback(
                failure = ReasoningOrchestrationFailure.AUDIT_COMMIT_FAILED,
                receipt = receipt,
                policyFailures = validation.failureCodes,
            )
        }
        if (policyRejected) {
            return safeFallback(
                failure = ReasoningOrchestrationFailure.POLICY_REJECTED,
                receipt = receipt,
                policyFailures = validation.failureCodes,
            )
        }
        if (validation.disposition == ReasoningDisposition.ABSTAIN) {
            return VerifiedReasoningOutcome(
                state = ReasoningDeliveryState.ABSTAINED,
                candidate = null,
                runReceipt = receipt,
                policyFailureCodes = emptySet(),
                orchestrationFailure = ReasoningOrchestrationFailure.NONE,
                authorityFailureCode = null,
                safeTemplateId = null,
            )
        }
        return VerifiedReasoningOutcome(
            state = ReasoningDeliveryState.DELIVERABLE,
            candidate = candidate,
            runReceipt = receipt,
            policyFailureCodes = emptySet(),
            orchestrationFailure = ReasoningOrchestrationFailure.NONE,
            authorityFailureCode = null,
            safeTemplateId = null,
        )
    }

    private fun authorityRejected(
        snapshotSha256: String,
        authorityFailure: HealthStateAuthorityFailureCode,
        receipt: OllamaRunReceipt? = null,
    ): VerifiedReasoningOutcome {
        val audit = ReasoningAuditRecord(
            inputSnapshotSha256 = snapshotSha256,
            candidateSha256 = null,
            disposition = ReasoningDisposition.ABSTAIN,
            policyFailureCodes = emptySet(),
            orchestrationFailure = ReasoningOrchestrationFailure.HEALTH_STATE_AUTHORITY_REJECTED,
            authorityFailureCode = authorityFailure,
            runReceipt = receipt,
            completedAtEpochMillis = nowEpochMillis(),
        )
        if (!auditSink.commit(audit)) {
            return safeFallback(ReasoningOrchestrationFailure.AUDIT_COMMIT_FAILED, receipt = receipt)
        }
        return safeFallback(
            failure = ReasoningOrchestrationFailure.HEALTH_STATE_AUTHORITY_REJECTED,
            receipt = receipt,
            authorityFailure = authorityFailure,
        )
    }

    private fun safeFallback(
        failure: ReasoningOrchestrationFailure,
        receipt: OllamaRunReceipt? = null,
        policyFailures: Set<ReasoningFailureCode> = emptySet(),
        authorityFailure: HealthStateAuthorityFailureCode? = null,
    ) = VerifiedReasoningOutcome(
        state = ReasoningDeliveryState.SAFE_FALLBACK,
        candidate = null,
        runReceipt = receipt,
        policyFailureCodes = policyFailures,
        orchestrationFailure = failure,
        authorityFailureCode = authorityFailure,
        safeTemplateId = "local-reasoning-unavailable-v1",
    )
}

/** Own one exact candidate before authority recheck, policy, hashing, audit or delivery. */
private fun LocalReasoningCandidate.immutableLocalSnapshot(): LocalReasoningCandidate = copy(
    claims = java.util.List.copyOf(claims.map { claim ->
        claim.copy(
            metricReferenceIds = java.util.List.copyOf(claim.metricReferenceIds),
            evidenceReferenceIds = java.util.List.copyOf(claim.evidenceReferenceIds),
            disconfirmingEvidenceReferenceIds = java.util.List.copyOf(
                claim.disconfirmingEvidenceReferenceIds,
            ),
        )
    }),
    nextMeasurementIds = java.util.List.copyOf(nextMeasurementIds),
    questionIdsForUser = java.util.List.copyOf(questionIdsForUser),
)
